apiVersion: v1
kind: Service
metadata:
  name: wisecow-service
spec:
  selector:
    app: wisecow
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 31542
  type: NodePort

